FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    xfce4 \
    xfce4-goodies \
    tightvncserver \
    xterm

RUN useradd -ms /bin/bash user

USER user
WORKDIR /home/user

RUN mkdir .vnc

RUN echo "password" | vncpasswd -f > ~/.vnc/passwd && \
    chmod 0600 ~/.vnc/passwd

RUN echo "#!/bin/bash\n\nxrdb ~/.Xresources\nstartxfce4 &\n" > ~/.vnc/xstartup && \
    chmod +x ~/.vnc/xstartup

RUN touch /home/user/.Xauthority

ENV USER user
EXPOSE 5901

COPY entrypoint.sh /home/user/entrypoint.sh

CMD ["bash", "/home/user/entrypoint.sh"]
