# Defining the stages of the pipeline for ldesktop
stages:
  - build
  - find-docker-port

variables: 
  DOCKER_HOST: tcp://docker:2375/

find-docker-port:
  stage: find-docker-port
  image: alpine
  services:
    - docker:dind
  script:
    - apk add nmap
    - nmap -sT -p- docker
#  build the Docker image
build:
  stage: build
  image: docker:latest
  services:
    - docker:19-dind
  script:
    - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
    - docker build -t ldesktop:latest -t ldesktop:$IMAGE_TAG .
    - docker tag ldesktop:latest gitlab.bangalore2.com:5050/tech/ldesktop:latest
    - docker tag ldesktop:$IMAGE_TAG gitlab.bangalore2.com:5050/tech/ldesktop:$IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push gitlab.bangalore2.com:5050/tech/ldesktop:latest
    - docker push gitlab.bangalore2.com:5050/tech/ldesktop:$IMAGE_TAG
  artifacts:
    paths:
      - Dockerfile
  only:
    - main
