# Defining the stages of the pipeline for ldesktop
stages:
  - build

variables: 
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


before_script:
  - docker info
#  build the Docker image
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
    - docker build -t ldesktop:latest -t ldesktop:$IMAGE_TAG .
    - docker tag ldesktop:latest gitlab.bangalore2.com:5050/tech/ldesktop:latest
    - docker tag ldesktop:$IMAGE_TAG gitlab.bangalore2.com:5050/tech/ldesktop:$IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push gitlab.bangalore2.com:5050/tech/ldesktop:latest
    - docker push gitlab.bangalore2.com:5050/tech/ldesktop:$IMAGE_TAG
  artifacts:
    paths:
      - Dockerfile
  only:
    - main
