version: '3'
services:
  vdi:
    container_name: vdi_app
    restart: always
    privileged: true
    image: asabhi6776/xdesktop:audio_update-1.1
    ports:
      - 5901:5901
      - 6080:6080
    volumes:
      - ./projects:/home/abhishek/Desktop/projects
    devices:
      - /dev/snd:/dev/snd
