version: '3'
services:
  vdi:
    container_name: vdi_app
    restart: always
    image: asabhi6776/xdesktop:latest
    ports:
      - 5901:5901
      - 6080:6080
    volumes:
      - ./projects:/home/abhishek/Desktop/projects
    mem_limit: "4g"
    cpus: 2
